spring:
  datasource:
   url: jdbc:sqlserver://localhost:1433;databaseName=DeskBookDev;encrypt=false
   username: sa
   password: Admin#123
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   # hibernate:
    #  ddl-auto: drop
   
